### PR TITLE
Add Issue and PR templates

### PR DESCRIPTION
**Pull request by jere-mie**

### CODE REVIEW

**Comment by jere-mie** [comment]
@zainaraza43 pls

**Comment by jere-mie** [comment]
@Brady-Malott please tell @zainaraza43 to accept my PR

**Comment by jere-mie** [comment]
@zainaraza43 let me know if you have any questions

**Review by prairir — APPROVED** [review]
approved mainly because I've edited these many many many times and use em all the time

**Comment by jere-mie** [comment]
We did it bois

**Pull request merged**
